### ISSUE TITLE
Complete basic functionality

### ISSUE THREAD

**Issue by vadim-zabolotniy** [JovianX/Service-Hub#55]
- [x] Sign up and login
- [x] Sign up and login with GitHub
- [x] Dashboard to indicate when there's no kubeconfig
- [x] Add your Kubeconfig (Translate YAML to JSON)
- [x] Deploy new Helm release
- [ ] Update Helm values of helm release 
- [x] Remove Helm release
- [x] Set / view TTL
- [x] Invite a team member

Advanced Feautes
- [x] Add Kubeconfig via CLI URL (Wizard)
- [ ] Context-based Rules
- [x] Deploy from Tempalte 
- [ ] Service monitoring
